api/firmware/device.go
After Reset(), all data should be reset. This especially fixes the
issue where channelHashDeviceVerified was true after the reset.
=> api/firmware: fix reset

api/firmware/device.go
- Use `SupportsETH()` only for Ethereum check and not tokens
- type check for messages.ETHCoin_ETH, messages.ETHCoin_RopstenETH
- and messages.ETHCoin_RinkebyETH instead of string
- Add `SupportsERC20()` function to check ERC20 support based on
- contract address
=> erc20-support: refactor SupportsETH to check ERC20 contract address

api/firmware/device.go, api/firmware/device_test.go, api/firmware/mocks/mocks.go, api/firmware/system.go
The call needs to be blocking due to the dialog on the device.
=> api/firmware: fix reboot regression

.golangci.yml, api/firmware/device.go, api/firmware/device_test.go, api/firmware/pairing.go
Since v7.0.0, the two initial noise handshake messages are framed:
request is prepended with 'H', response is prepended with
OP_STATUS_SUCCESS/OP_STATUS_FAILURE.
Since v4.0.0, encrypted noise message requests were framed with
OP_NOISE_MSG, but since v7.0.0, the response is also framed with
OP_STATUS_SUCCESS/OP_STATUS_FAILURE.
=> api/firmware: add noise handhshake framing and response framing

api/firmware/device.go
Contains a required bugfix for MEW and a required new api call for
Electrum (ElectrumEncryptionKey).
=> api/firmware: min version must be 6.1.0

api/firmware/query.go, go.mod, go.sum
Autoimported github.com/gogo/protobuf/proto instead of github.com/golang/protobuf/proto instead.
=> api/firmware: fix wrong gomod import

api/firmware/query.go
The retry api was just the retry op code, without the msg appended.
=> api/firmware: fix retry query api

api/firmware/attestation.go
According to https://github.com/digitalbitbox/bitbox02-firmware/pull/630.
=> firmware: add attestation keys

.travis.yml
GopherJS is stuck on go1.12 and because we use it to generate api-js,
need to ensure this still compiles.
The other one, go1.14, is to make sure we will be able to build it when
GopherJS is finally unstuck.
=> ci: run on both go1.14 and go1.12 for GopherJS

api/firmware/device.go
Since 6.0.0, a lot more tokens are supported. For now, this list only
contains tokens relevant to the BitBoxApp, otherwise the
bitbox02-api-js library size would blow up.
Later we can think about moving this whole piece to the
bitbox-wallet-app repo instead, as figure out what to do in this
library if any other downstream project needs such a check.
=> firmware/device: add WBTC, PAXG erc20 tokens

api/firmware/eth.go
The use of this offset for uncompressed pubkeys started in Bitcoin,
and in Ethereum, usage is inconsistent.
MyEtherWallet supports both when verifying:
https://github.com/MyEtherWallet/MyEtherWallet/blob/052f697f3b269db4378f331dbb89d24b406bb7c7/src/components/VerifyMessageInput/VerifyMessageInput.vue#L118
Trezor adds this offset as well.
The testing.aopp.group AOPP demo site requires the offset.
=> firmware/eth: add offset of 27 when signing a message

api/firmware/device.go
This adds Goerli testnet chain ID between those which are supported, starting from FW version 9.10.0.
=> firmware: added support to Goerli ETH testnet.

api/firmware/mnemonic.go
This will help with determining if someone used the passphrase, which is often the cause of "missing funds" (when using the wrong passphrase).
=> api/firwmare/mnemonic: log when passphrase is enabled/disabled

communication/u2fhid/u2fhid.go
The CID in the response is compared against the hardcoded 0xff000000 CID. It should however parse and compare it to the const `cid`. This allows us to change the CID (i.e. make it random) and not break parsing.
=> communication/u2fhid: don't hardcode CID check in response

communication/u2fhid/u2fhid.go
Compiling this using gomobile for Android gave this error:
```
u2fhid.go:158:62: cannot use cid (untyped int constant 4278190080) as int value in argument to errp.Newf (overflows)
```
Must be some bug in gomobile.
=> communication/u2fhid: type the cid constant

.github/workflows/ci.yml, .golangci.yml, api/bootloader/device.go, api/firmware/device.go, api/firmware/event.go, communication/usart/usart_internal_test.go
This change is needed as GitHub deprecated ubuntu-18.04:
>  The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04 or ubuntu-22.04 (ubuntu-latest). For more details, see https://github.com/actions/runner-images/issues/6002
=> .github/workflows/ci.yml: update to ubuntu-22.04

api/firmware/query.go
The previous 'unexpected NACK response; last successful query..' log line wasn't really useful as it was logging the time between the last `hwwRspNotready` and the next (and last) `hwwRspNack` responses. We actually want to log the interval between the `hwwReqRetry` requests, that can cause the Nack response (if happening with more than 500ms delay).
With this change, we use a circular buffer and keep trace of the timing interval of the last 10 retry requests, to better investigate usb timing issues.
=> firmware/query: improve last usb query intervals log

api/firmware/eth.go, api/firmware/eth_test.go, cmd/playground/main.go
Some apps use EIP-712 typed messages but provide uints in hex format instead of decimal format.
=> api/firmware/eth: parse eth eip-712 uints as hex

api/bootloader/device.go, api/bootloader/util.go, api/bootloader/util_test.go
Useful to compute a firmware hash from a firmware binary to compare it against the result of `device.GetHashes()`, to see if the device has a certain firmware installed or not.
=> api/bootloader: add HashFirmware and ParseSignedFirmware util functions

cmd/paymentrequest/main.go
Easier to mess with the example.
=> cmd/paymentrequest: dynamically sign the payment request

api/firmware/sdcard.go, api/firmware/sdcard_test.go
It will be removed from the firmware as we never ended up using it.
=> api/firmware: remove "remove sdcard" functionality

api/firmware/btc.go, api/firmware/btc_test.go
Otherwise an outdated firmware would just return "generic error" when running into such an output.
=> firmware/btc: return nice error message if silent payments not supported

cmd/miniscript/main.go, cmd/paymentrequest/main.go, cmd/playground/main.go, go.mod, go.sum
More up to date, same dep as in the BitBoxApp. The old one does not work on newer macOS versions.
This is only in the demo/helper cmd scripts, not part of the main library.
=> deps: replace karabale/usb with karalabe/hid

api/firmware/query.go, util/sleep/sleep.go, util/sleep/sleep_darwin.go
When doing long interactions on the device, e.g. recovering from 24 words, and macOS goes to sleep, USB interaction would be slowed down and the workflow would be aborted.
This commit prevents this from happening by preventing macOS from going to sleep during such an interaction.
The alternative was to expose callbacks here and let the BitBoxApp (and other users) implement the callbacks, but it seems like every app that uses this lib would want this. In case not, we add a build flag if not desired.
=> api/firmware: prevent sleep on macOS during long running queries

util/sleep/sleep.go, util/sleep/sleep_macos.go
The previous filters would also compile the sleep_darwin.go file for iOS, failing compilation, as the `darwin` build tag also matches on iOS:
https://pkg.go.dev/cmd/go
```
Using GOOS=ios matches build tags and files as for GOOS=darwin in
addition to ios tags and files.
```
We need to exclude iOS explicitly here.
=> util/sleep: exclude iOS

.github/workflows/ci.yml, .golangci.yml, api/bootloader/device_test.go, api/firmware/device_test.go, api/firmware/query.go, communication/usart/usart_test.go, go.mod, util/semver/semver.go
golangci.yml was cleaned up basd on warnings it printed.
Go 1.22 because it fixes the loop reference reuse.
=> update min Go version to 1.22 and update golangci, fix lints

api/bootloader/device.go, api/bootloader/device_test.go, api/common/common.go, api/firmware/device.go, api/firmware/device_test.go, api/firmware/pairing.go, cmd/bootloader/main.go, cmd/miniscript/main.go, cmd/paymentrequest/main.go, cmd/playground/main.go
Allows the BitBoxApp to detect the product. These might be placeholder values to be renamed later.
The existing product names are prefixed with BitBox02 for disambiguation.
Standard is renamed to Multi, as that's what the product is actually named.
HID is renamed to Device, as the string is not only used in HID descriptors, but also in the Bluetooth characteristic.
=> common: add product strings for BitBox02Plus

api/firmware/btc.go, api/firmware/btc_test.go, cmd/miniscript/main.go, cmd/paymentrequest/main.go, cmd/playground/main.go
Better clarity and composes better with generic functions returning a single value.
=> firmware/btc: return struct in BTCSign and BTCSignMessage

communication/u2fhid/u2fhid.go, communication/u2fhid/u2fhid_test.go
To be more efficient multiple u2fhid packets are written simultaneously if possible
Should be carefully tested on all platforms. A good test is the firmware upgrade as it for sure tries to send larger packets.
=> u2fhid: Write as many bytes as possible

api/firmware/system.go
Since the communication is cut after a reset, one can't reuse the instance. See also: https://github.com/BitBoxSwiss/bitbox-wallet-app/pull/3403.
=> firmware: update docstring

cmd/bluetooth_upgrade/main.go, cmd/bootloader/main.go, cmd/miniscript/main.go, cmd/paymentrequest/main.go, cmd/playground/main.go, communication/u2fhid/hiddevice.go
=> u2fhid: add hid.Device wrapper to fix IOKit timeouts on macOS

api/firmware/psbt.go, api/firmware/psbt_test.go
The PSBT contains all the info to be able to tell the BitBox if an output belongs to the same keystore, and if so, if it belongs to the same account or a different account. Depending on which it is, we add the scriptConfig to the input script configs or to the output script configs.
There is some complication with maintaining backwards compatbility, as the BitBox did not always accept non-change internal outputs or internal outputs belonging to a different account. In these cases, the output is confirmed as a regular outgoing payment.
=> psbt: infer send-to-self data from PSBT
